// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: BooleanProto.proto

package org.grpc.proto;

public final class BooleanProtoOuterClass {
  private BooleanProtoOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface BooleanProtoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:BooleanProto)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>bool isExist = 1;</code>
     */
    boolean getIsExist();
  }
  /**
   * Protobuf type {@code BooleanProto}
   */
  public  static final class BooleanProto extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:BooleanProto)
      BooleanProtoOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use BooleanProto.newBuilder() to construct.
    private BooleanProto(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private BooleanProto() {
      isExist_ = false;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private BooleanProto(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              isExist_ = input.readBool();
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.grpc.proto.BooleanProtoOuterClass.internal_static_BooleanProto_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.grpc.proto.BooleanProtoOuterClass.internal_static_BooleanProto_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.grpc.proto.BooleanProtoOuterClass.BooleanProto.class, org.grpc.proto.BooleanProtoOuterClass.BooleanProto.Builder.class);
    }

    public static final int ISEXIST_FIELD_NUMBER = 1;
    private boolean isExist_;
    /**
     * <code>bool isExist = 1;</code>
     */
    public boolean getIsExist() {
      return isExist_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (isExist_ != false) {
        output.writeBool(1, isExist_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (isExist_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(1, isExist_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.grpc.proto.BooleanProtoOuterClass.BooleanProto)) {
        return super.equals(obj);
      }
      org.grpc.proto.BooleanProtoOuterClass.BooleanProto other = (org.grpc.proto.BooleanProtoOuterClass.BooleanProto) obj;

      boolean result = true;
      result = result && (getIsExist()
          == other.getIsExist());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ISEXIST_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getIsExist());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.grpc.proto.BooleanProtoOuterClass.BooleanProto parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.grpc.proto.BooleanProtoOuterClass.BooleanProto parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.grpc.proto.BooleanProtoOuterClass.BooleanProto parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.grpc.proto.BooleanProtoOuterClass.BooleanProto parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.grpc.proto.BooleanProtoOuterClass.BooleanProto parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.grpc.proto.BooleanProtoOuterClass.BooleanProto parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.grpc.proto.BooleanProtoOuterClass.BooleanProto parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.grpc.proto.BooleanProtoOuterClass.BooleanProto parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.grpc.proto.BooleanProtoOuterClass.BooleanProto parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static org.grpc.proto.BooleanProtoOuterClass.BooleanProto parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.grpc.proto.BooleanProtoOuterClass.BooleanProto parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.grpc.proto.BooleanProtoOuterClass.BooleanProto parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.grpc.proto.BooleanProtoOuterClass.BooleanProto prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code BooleanProto}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:BooleanProto)
        org.grpc.proto.BooleanProtoOuterClass.BooleanProtoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.grpc.proto.BooleanProtoOuterClass.internal_static_BooleanProto_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.grpc.proto.BooleanProtoOuterClass.internal_static_BooleanProto_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.grpc.proto.BooleanProtoOuterClass.BooleanProto.class, org.grpc.proto.BooleanProtoOuterClass.BooleanProto.Builder.class);
      }

      // Construct using org.grpc.proto.BooleanProtoOuterClass.BooleanProto.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        isExist_ = false;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.grpc.proto.BooleanProtoOuterClass.internal_static_BooleanProto_descriptor;
      }

      @java.lang.Override
      public org.grpc.proto.BooleanProtoOuterClass.BooleanProto getDefaultInstanceForType() {
        return org.grpc.proto.BooleanProtoOuterClass.BooleanProto.getDefaultInstance();
      }

      @java.lang.Override
      public org.grpc.proto.BooleanProtoOuterClass.BooleanProto build() {
        org.grpc.proto.BooleanProtoOuterClass.BooleanProto result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public org.grpc.proto.BooleanProtoOuterClass.BooleanProto buildPartial() {
        org.grpc.proto.BooleanProtoOuterClass.BooleanProto result = new org.grpc.proto.BooleanProtoOuterClass.BooleanProto(this);
        result.isExist_ = isExist_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.grpc.proto.BooleanProtoOuterClass.BooleanProto) {
          return mergeFrom((org.grpc.proto.BooleanProtoOuterClass.BooleanProto)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.grpc.proto.BooleanProtoOuterClass.BooleanProto other) {
        if (other == org.grpc.proto.BooleanProtoOuterClass.BooleanProto.getDefaultInstance()) return this;
        if (other.getIsExist() != false) {
          setIsExist(other.getIsExist());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.grpc.proto.BooleanProtoOuterClass.BooleanProto parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.grpc.proto.BooleanProtoOuterClass.BooleanProto) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private boolean isExist_ ;
      /**
       * <code>bool isExist = 1;</code>
       */
      public boolean getIsExist() {
        return isExist_;
      }
      /**
       * <code>bool isExist = 1;</code>
       */
      public Builder setIsExist(boolean value) {
        
        isExist_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bool isExist = 1;</code>
       */
      public Builder clearIsExist() {
        
        isExist_ = false;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:BooleanProto)
    }

    // @@protoc_insertion_point(class_scope:BooleanProto)
    private static final org.grpc.proto.BooleanProtoOuterClass.BooleanProto DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.grpc.proto.BooleanProtoOuterClass.BooleanProto();
    }

    public static org.grpc.proto.BooleanProtoOuterClass.BooleanProto getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<BooleanProto>
        PARSER = new com.google.protobuf.AbstractParser<BooleanProto>() {
      @java.lang.Override
      public BooleanProto parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new BooleanProto(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<BooleanProto> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<BooleanProto> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public org.grpc.proto.BooleanProtoOuterClass.BooleanProto getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_BooleanProto_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_BooleanProto_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022BooleanProto.proto\"\037\n\014BooleanProto\022\017\n\007" +
      "isExist\030\001 \001(\010B\020\n\016org.grpc.protob\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_BooleanProto_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_BooleanProto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_BooleanProto_descriptor,
        new java.lang.String[] { "IsExist", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
