// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: CacheElasticProcessService.proto

package org.grpc.proto;

public final class CacheElasticProcessService {
  private CacheElasticProcessService() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n CacheElasticProcessService.proto\032\036Cach" +
      "eElasticProcessQueue.proto\032\rIdProto.prot" +
      "o\032\021IdListProto.proto\032\013Empty.proto\032%Cache" +
      "ElasticProcessQueueIdProto.proto2\264\002\n\037Cac" +
      "heElasticProcessQueueService\022Z\n\033addCache" +
      "ElasticProcessQueue\022\031.CacheElasticProces" +
      "sQueue\032 .CacheElasticProcessQueueIdProto" +
      "\022\"\n\nfindQueued\022\006.Empty\032\014.IdListProto\022B\n\033" +
      "getCacheElasticProcessQueue\022\010.IdProto\032\031." +
      "CacheElasticProcessQueue\022&\n\016findHangingI" +
      "ds\022\006.Empty\032\014.IdListProto\022%\n\021queuedHangin" +
      "gById\022\010.IdProto\032\006.EmptyB\020\n\016org.grpc.prot" +
      "ob\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          org.grpc.proto.CacheElasticProcessQueueOuterClass.getDescriptor(),
          org.grpc.proto.IdProtoOuterClass.getDescriptor(),
          org.grpc.proto.IdListProtoOuterClass.getDescriptor(),
          org.grpc.proto.EmptyOuterClass.getDescriptor(),
          org.grpc.proto.CacheElasticProcessQueueIdProtoOuterClass.getDescriptor(),
        }, assigner);
    org.grpc.proto.CacheElasticProcessQueueOuterClass.getDescriptor();
    org.grpc.proto.IdProtoOuterClass.getDescriptor();
    org.grpc.proto.IdListProtoOuterClass.getDescriptor();
    org.grpc.proto.EmptyOuterClass.getDescriptor();
    org.grpc.proto.CacheElasticProcessQueueIdProtoOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
