// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: CacheElasticProcessQueue.proto

package org.grpc.proto;

public final class CacheElasticProcessQueueOuterClass {
  private CacheElasticProcessQueueOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface CacheElasticProcessQueueOrBuilder extends
      // @@protoc_insertion_point(interface_extends:CacheElasticProcessQueue)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int64 id = 1;</code>
     */
    long getId();

    /**
     * <code>string createdAt = 2;</code>
     */
    java.lang.String getCreatedAt();
    /**
     * <code>string createdAt = 2;</code>
     */
    com.google.protobuf.ByteString
        getCreatedAtBytes();

    /**
     * <code>string updatedAt = 3;</code>
     */
    java.lang.String getUpdatedAt();
    /**
     * <code>string updatedAt = 3;</code>
     */
    com.google.protobuf.ByteString
        getUpdatedAtBytes();

    /**
     * <code>int32 status = 4;</code>
     */
    int getStatus();

    /**
     * <code>int32 archiveStatus = 5;</code>
     */
    int getArchiveStatus();

    /**
     * <code>int32 processSource = 6;</code>
     */
    int getProcessSource();

    /**
     * <code>string errorMessage = 7;</code>
     */
    java.lang.String getErrorMessage();
    /**
     * <code>string errorMessage = 7;</code>
     */
    com.google.protobuf.ByteString
        getErrorMessageBytes();

    /**
     * <code>string action = 8;</code>
     */
    java.lang.String getAction();
    /**
     * <code>string action = 8;</code>
     */
    com.google.protobuf.ByteString
        getActionBytes();

    /**
     * <code>string model = 9;</code>
     */
    java.lang.String getModel();
    /**
     * <code>string model = 9;</code>
     */
    com.google.protobuf.ByteString
        getModelBytes();

    /**
     * <code>string requestString = 10;</code>
     */
    java.lang.String getRequestString();
    /**
     * <code>string requestString = 10;</code>
     */
    com.google.protobuf.ByteString
        getRequestStringBytes();

    /**
     * <code>int64 userId = 11;</code>
     */
    long getUserId();
  }
  /**
   * Protobuf type {@code CacheElasticProcessQueue}
   */
  public  static final class CacheElasticProcessQueue extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:CacheElasticProcessQueue)
      CacheElasticProcessQueueOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use CacheElasticProcessQueue.newBuilder() to construct.
    private CacheElasticProcessQueue(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private CacheElasticProcessQueue() {
      id_ = 0L;
      createdAt_ = "";
      updatedAt_ = "";
      status_ = 0;
      archiveStatus_ = 0;
      processSource_ = 0;
      errorMessage_ = "";
      action_ = "";
      model_ = "";
      requestString_ = "";
      userId_ = 0L;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private CacheElasticProcessQueue(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              id_ = input.readInt64();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              createdAt_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              updatedAt_ = s;
              break;
            }
            case 32: {

              status_ = input.readInt32();
              break;
            }
            case 40: {

              archiveStatus_ = input.readInt32();
              break;
            }
            case 48: {

              processSource_ = input.readInt32();
              break;
            }
            case 58: {
              java.lang.String s = input.readStringRequireUtf8();

              errorMessage_ = s;
              break;
            }
            case 66: {
              java.lang.String s = input.readStringRequireUtf8();

              action_ = s;
              break;
            }
            case 74: {
              java.lang.String s = input.readStringRequireUtf8();

              model_ = s;
              break;
            }
            case 82: {
              java.lang.String s = input.readStringRequireUtf8();

              requestString_ = s;
              break;
            }
            case 88: {

              userId_ = input.readInt64();
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.grpc.proto.CacheElasticProcessQueueOuterClass.internal_static_CacheElasticProcessQueue_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.grpc.proto.CacheElasticProcessQueueOuterClass.internal_static_CacheElasticProcessQueue_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.grpc.proto.CacheElasticProcessQueueOuterClass.CacheElasticProcessQueue.class, org.grpc.proto.CacheElasticProcessQueueOuterClass.CacheElasticProcessQueue.Builder.class);
    }

    public static final int ID_FIELD_NUMBER = 1;
    private long id_;
    /**
     * <code>int64 id = 1;</code>
     */
    public long getId() {
      return id_;
    }

    public static final int CREATEDAT_FIELD_NUMBER = 2;
    private volatile java.lang.Object createdAt_;
    /**
     * <code>string createdAt = 2;</code>
     */
    public java.lang.String getCreatedAt() {
      java.lang.Object ref = createdAt_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        createdAt_ = s;
        return s;
      }
    }
    /**
     * <code>string createdAt = 2;</code>
     */
    public com.google.protobuf.ByteString
        getCreatedAtBytes() {
      java.lang.Object ref = createdAt_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        createdAt_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int UPDATEDAT_FIELD_NUMBER = 3;
    private volatile java.lang.Object updatedAt_;
    /**
     * <code>string updatedAt = 3;</code>
     */
    public java.lang.String getUpdatedAt() {
      java.lang.Object ref = updatedAt_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        updatedAt_ = s;
        return s;
      }
    }
    /**
     * <code>string updatedAt = 3;</code>
     */
    public com.google.protobuf.ByteString
        getUpdatedAtBytes() {
      java.lang.Object ref = updatedAt_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        updatedAt_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int STATUS_FIELD_NUMBER = 4;
    private int status_;
    /**
     * <code>int32 status = 4;</code>
     */
    public int getStatus() {
      return status_;
    }

    public static final int ARCHIVESTATUS_FIELD_NUMBER = 5;
    private int archiveStatus_;
    /**
     * <code>int32 archiveStatus = 5;</code>
     */
    public int getArchiveStatus() {
      return archiveStatus_;
    }

    public static final int PROCESSSOURCE_FIELD_NUMBER = 6;
    private int processSource_;
    /**
     * <code>int32 processSource = 6;</code>
     */
    public int getProcessSource() {
      return processSource_;
    }

    public static final int ERRORMESSAGE_FIELD_NUMBER = 7;
    private volatile java.lang.Object errorMessage_;
    /**
     * <code>string errorMessage = 7;</code>
     */
    public java.lang.String getErrorMessage() {
      java.lang.Object ref = errorMessage_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        errorMessage_ = s;
        return s;
      }
    }
    /**
     * <code>string errorMessage = 7;</code>
     */
    public com.google.protobuf.ByteString
        getErrorMessageBytes() {
      java.lang.Object ref = errorMessage_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        errorMessage_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ACTION_FIELD_NUMBER = 8;
    private volatile java.lang.Object action_;
    /**
     * <code>string action = 8;</code>
     */
    public java.lang.String getAction() {
      java.lang.Object ref = action_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        action_ = s;
        return s;
      }
    }
    /**
     * <code>string action = 8;</code>
     */
    public com.google.protobuf.ByteString
        getActionBytes() {
      java.lang.Object ref = action_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        action_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int MODEL_FIELD_NUMBER = 9;
    private volatile java.lang.Object model_;
    /**
     * <code>string model = 9;</code>
     */
    public java.lang.String getModel() {
      java.lang.Object ref = model_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        model_ = s;
        return s;
      }
    }
    /**
     * <code>string model = 9;</code>
     */
    public com.google.protobuf.ByteString
        getModelBytes() {
      java.lang.Object ref = model_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        model_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int REQUESTSTRING_FIELD_NUMBER = 10;
    private volatile java.lang.Object requestString_;
    /**
     * <code>string requestString = 10;</code>
     */
    public java.lang.String getRequestString() {
      java.lang.Object ref = requestString_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        requestString_ = s;
        return s;
      }
    }
    /**
     * <code>string requestString = 10;</code>
     */
    public com.google.protobuf.ByteString
        getRequestStringBytes() {
      java.lang.Object ref = requestString_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        requestString_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int USERID_FIELD_NUMBER = 11;
    private long userId_;
    /**
     * <code>int64 userId = 11;</code>
     */
    public long getUserId() {
      return userId_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (id_ != 0L) {
        output.writeInt64(1, id_);
      }
      if (!getCreatedAtBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, createdAt_);
      }
      if (!getUpdatedAtBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, updatedAt_);
      }
      if (status_ != 0) {
        output.writeInt32(4, status_);
      }
      if (archiveStatus_ != 0) {
        output.writeInt32(5, archiveStatus_);
      }
      if (processSource_ != 0) {
        output.writeInt32(6, processSource_);
      }
      if (!getErrorMessageBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 7, errorMessage_);
      }
      if (!getActionBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 8, action_);
      }
      if (!getModelBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 9, model_);
      }
      if (!getRequestStringBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 10, requestString_);
      }
      if (userId_ != 0L) {
        output.writeInt64(11, userId_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (id_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, id_);
      }
      if (!getCreatedAtBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, createdAt_);
      }
      if (!getUpdatedAtBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, updatedAt_);
      }
      if (status_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, status_);
      }
      if (archiveStatus_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, archiveStatus_);
      }
      if (processSource_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(6, processSource_);
      }
      if (!getErrorMessageBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, errorMessage_);
      }
      if (!getActionBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(8, action_);
      }
      if (!getModelBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(9, model_);
      }
      if (!getRequestStringBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(10, requestString_);
      }
      if (userId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(11, userId_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.grpc.proto.CacheElasticProcessQueueOuterClass.CacheElasticProcessQueue)) {
        return super.equals(obj);
      }
      org.grpc.proto.CacheElasticProcessQueueOuterClass.CacheElasticProcessQueue other = (org.grpc.proto.CacheElasticProcessQueueOuterClass.CacheElasticProcessQueue) obj;

      boolean result = true;
      result = result && (getId()
          == other.getId());
      result = result && getCreatedAt()
          .equals(other.getCreatedAt());
      result = result && getUpdatedAt()
          .equals(other.getUpdatedAt());
      result = result && (getStatus()
          == other.getStatus());
      result = result && (getArchiveStatus()
          == other.getArchiveStatus());
      result = result && (getProcessSource()
          == other.getProcessSource());
      result = result && getErrorMessage()
          .equals(other.getErrorMessage());
      result = result && getAction()
          .equals(other.getAction());
      result = result && getModel()
          .equals(other.getModel());
      result = result && getRequestString()
          .equals(other.getRequestString());
      result = result && (getUserId()
          == other.getUserId());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getId());
      hash = (37 * hash) + CREATEDAT_FIELD_NUMBER;
      hash = (53 * hash) + getCreatedAt().hashCode();
      hash = (37 * hash) + UPDATEDAT_FIELD_NUMBER;
      hash = (53 * hash) + getUpdatedAt().hashCode();
      hash = (37 * hash) + STATUS_FIELD_NUMBER;
      hash = (53 * hash) + getStatus();
      hash = (37 * hash) + ARCHIVESTATUS_FIELD_NUMBER;
      hash = (53 * hash) + getArchiveStatus();
      hash = (37 * hash) + PROCESSSOURCE_FIELD_NUMBER;
      hash = (53 * hash) + getProcessSource();
      hash = (37 * hash) + ERRORMESSAGE_FIELD_NUMBER;
      hash = (53 * hash) + getErrorMessage().hashCode();
      hash = (37 * hash) + ACTION_FIELD_NUMBER;
      hash = (53 * hash) + getAction().hashCode();
      hash = (37 * hash) + MODEL_FIELD_NUMBER;
      hash = (53 * hash) + getModel().hashCode();
      hash = (37 * hash) + REQUESTSTRING_FIELD_NUMBER;
      hash = (53 * hash) + getRequestString().hashCode();
      hash = (37 * hash) + USERID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getUserId());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.grpc.proto.CacheElasticProcessQueueOuterClass.CacheElasticProcessQueue parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.grpc.proto.CacheElasticProcessQueueOuterClass.CacheElasticProcessQueue parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.grpc.proto.CacheElasticProcessQueueOuterClass.CacheElasticProcessQueue parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.grpc.proto.CacheElasticProcessQueueOuterClass.CacheElasticProcessQueue parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.grpc.proto.CacheElasticProcessQueueOuterClass.CacheElasticProcessQueue parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.grpc.proto.CacheElasticProcessQueueOuterClass.CacheElasticProcessQueue parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.grpc.proto.CacheElasticProcessQueueOuterClass.CacheElasticProcessQueue parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.grpc.proto.CacheElasticProcessQueueOuterClass.CacheElasticProcessQueue parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.grpc.proto.CacheElasticProcessQueueOuterClass.CacheElasticProcessQueue parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static org.grpc.proto.CacheElasticProcessQueueOuterClass.CacheElasticProcessQueue parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.grpc.proto.CacheElasticProcessQueueOuterClass.CacheElasticProcessQueue parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.grpc.proto.CacheElasticProcessQueueOuterClass.CacheElasticProcessQueue parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.grpc.proto.CacheElasticProcessQueueOuterClass.CacheElasticProcessQueue prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code CacheElasticProcessQueue}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:CacheElasticProcessQueue)
        org.grpc.proto.CacheElasticProcessQueueOuterClass.CacheElasticProcessQueueOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.grpc.proto.CacheElasticProcessQueueOuterClass.internal_static_CacheElasticProcessQueue_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.grpc.proto.CacheElasticProcessQueueOuterClass.internal_static_CacheElasticProcessQueue_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.grpc.proto.CacheElasticProcessQueueOuterClass.CacheElasticProcessQueue.class, org.grpc.proto.CacheElasticProcessQueueOuterClass.CacheElasticProcessQueue.Builder.class);
      }

      // Construct using org.grpc.proto.CacheElasticProcessQueueOuterClass.CacheElasticProcessQueue.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        id_ = 0L;

        createdAt_ = "";

        updatedAt_ = "";

        status_ = 0;

        archiveStatus_ = 0;

        processSource_ = 0;

        errorMessage_ = "";

        action_ = "";

        model_ = "";

        requestString_ = "";

        userId_ = 0L;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.grpc.proto.CacheElasticProcessQueueOuterClass.internal_static_CacheElasticProcessQueue_descriptor;
      }

      @java.lang.Override
      public org.grpc.proto.CacheElasticProcessQueueOuterClass.CacheElasticProcessQueue getDefaultInstanceForType() {
        return org.grpc.proto.CacheElasticProcessQueueOuterClass.CacheElasticProcessQueue.getDefaultInstance();
      }

      @java.lang.Override
      public org.grpc.proto.CacheElasticProcessQueueOuterClass.CacheElasticProcessQueue build() {
        org.grpc.proto.CacheElasticProcessQueueOuterClass.CacheElasticProcessQueue result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public org.grpc.proto.CacheElasticProcessQueueOuterClass.CacheElasticProcessQueue buildPartial() {
        org.grpc.proto.CacheElasticProcessQueueOuterClass.CacheElasticProcessQueue result = new org.grpc.proto.CacheElasticProcessQueueOuterClass.CacheElasticProcessQueue(this);
        result.id_ = id_;
        result.createdAt_ = createdAt_;
        result.updatedAt_ = updatedAt_;
        result.status_ = status_;
        result.archiveStatus_ = archiveStatus_;
        result.processSource_ = processSource_;
        result.errorMessage_ = errorMessage_;
        result.action_ = action_;
        result.model_ = model_;
        result.requestString_ = requestString_;
        result.userId_ = userId_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.grpc.proto.CacheElasticProcessQueueOuterClass.CacheElasticProcessQueue) {
          return mergeFrom((org.grpc.proto.CacheElasticProcessQueueOuterClass.CacheElasticProcessQueue)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.grpc.proto.CacheElasticProcessQueueOuterClass.CacheElasticProcessQueue other) {
        if (other == org.grpc.proto.CacheElasticProcessQueueOuterClass.CacheElasticProcessQueue.getDefaultInstance()) return this;
        if (other.getId() != 0L) {
          setId(other.getId());
        }
        if (!other.getCreatedAt().isEmpty()) {
          createdAt_ = other.createdAt_;
          onChanged();
        }
        if (!other.getUpdatedAt().isEmpty()) {
          updatedAt_ = other.updatedAt_;
          onChanged();
        }
        if (other.getStatus() != 0) {
          setStatus(other.getStatus());
        }
        if (other.getArchiveStatus() != 0) {
          setArchiveStatus(other.getArchiveStatus());
        }
        if (other.getProcessSource() != 0) {
          setProcessSource(other.getProcessSource());
        }
        if (!other.getErrorMessage().isEmpty()) {
          errorMessage_ = other.errorMessage_;
          onChanged();
        }
        if (!other.getAction().isEmpty()) {
          action_ = other.action_;
          onChanged();
        }
        if (!other.getModel().isEmpty()) {
          model_ = other.model_;
          onChanged();
        }
        if (!other.getRequestString().isEmpty()) {
          requestString_ = other.requestString_;
          onChanged();
        }
        if (other.getUserId() != 0L) {
          setUserId(other.getUserId());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.grpc.proto.CacheElasticProcessQueueOuterClass.CacheElasticProcessQueue parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.grpc.proto.CacheElasticProcessQueueOuterClass.CacheElasticProcessQueue) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private long id_ ;
      /**
       * <code>int64 id = 1;</code>
       */
      public long getId() {
        return id_;
      }
      /**
       * <code>int64 id = 1;</code>
       */
      public Builder setId(long value) {
        
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 id = 1;</code>
       */
      public Builder clearId() {
        
        id_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object createdAt_ = "";
      /**
       * <code>string createdAt = 2;</code>
       */
      public java.lang.String getCreatedAt() {
        java.lang.Object ref = createdAt_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          createdAt_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string createdAt = 2;</code>
       */
      public com.google.protobuf.ByteString
          getCreatedAtBytes() {
        java.lang.Object ref = createdAt_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          createdAt_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string createdAt = 2;</code>
       */
      public Builder setCreatedAt(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        createdAt_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string createdAt = 2;</code>
       */
      public Builder clearCreatedAt() {
        
        createdAt_ = getDefaultInstance().getCreatedAt();
        onChanged();
        return this;
      }
      /**
       * <code>string createdAt = 2;</code>
       */
      public Builder setCreatedAtBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        createdAt_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object updatedAt_ = "";
      /**
       * <code>string updatedAt = 3;</code>
       */
      public java.lang.String getUpdatedAt() {
        java.lang.Object ref = updatedAt_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          updatedAt_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string updatedAt = 3;</code>
       */
      public com.google.protobuf.ByteString
          getUpdatedAtBytes() {
        java.lang.Object ref = updatedAt_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          updatedAt_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string updatedAt = 3;</code>
       */
      public Builder setUpdatedAt(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        updatedAt_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string updatedAt = 3;</code>
       */
      public Builder clearUpdatedAt() {
        
        updatedAt_ = getDefaultInstance().getUpdatedAt();
        onChanged();
        return this;
      }
      /**
       * <code>string updatedAt = 3;</code>
       */
      public Builder setUpdatedAtBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        updatedAt_ = value;
        onChanged();
        return this;
      }

      private int status_ ;
      /**
       * <code>int32 status = 4;</code>
       */
      public int getStatus() {
        return status_;
      }
      /**
       * <code>int32 status = 4;</code>
       */
      public Builder setStatus(int value) {
        
        status_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 status = 4;</code>
       */
      public Builder clearStatus() {
        
        status_ = 0;
        onChanged();
        return this;
      }

      private int archiveStatus_ ;
      /**
       * <code>int32 archiveStatus = 5;</code>
       */
      public int getArchiveStatus() {
        return archiveStatus_;
      }
      /**
       * <code>int32 archiveStatus = 5;</code>
       */
      public Builder setArchiveStatus(int value) {
        
        archiveStatus_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 archiveStatus = 5;</code>
       */
      public Builder clearArchiveStatus() {
        
        archiveStatus_ = 0;
        onChanged();
        return this;
      }

      private int processSource_ ;
      /**
       * <code>int32 processSource = 6;</code>
       */
      public int getProcessSource() {
        return processSource_;
      }
      /**
       * <code>int32 processSource = 6;</code>
       */
      public Builder setProcessSource(int value) {
        
        processSource_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 processSource = 6;</code>
       */
      public Builder clearProcessSource() {
        
        processSource_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object errorMessage_ = "";
      /**
       * <code>string errorMessage = 7;</code>
       */
      public java.lang.String getErrorMessage() {
        java.lang.Object ref = errorMessage_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          errorMessage_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string errorMessage = 7;</code>
       */
      public com.google.protobuf.ByteString
          getErrorMessageBytes() {
        java.lang.Object ref = errorMessage_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          errorMessage_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string errorMessage = 7;</code>
       */
      public Builder setErrorMessage(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        errorMessage_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string errorMessage = 7;</code>
       */
      public Builder clearErrorMessage() {
        
        errorMessage_ = getDefaultInstance().getErrorMessage();
        onChanged();
        return this;
      }
      /**
       * <code>string errorMessage = 7;</code>
       */
      public Builder setErrorMessageBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        errorMessage_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object action_ = "";
      /**
       * <code>string action = 8;</code>
       */
      public java.lang.String getAction() {
        java.lang.Object ref = action_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          action_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string action = 8;</code>
       */
      public com.google.protobuf.ByteString
          getActionBytes() {
        java.lang.Object ref = action_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          action_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string action = 8;</code>
       */
      public Builder setAction(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        action_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string action = 8;</code>
       */
      public Builder clearAction() {
        
        action_ = getDefaultInstance().getAction();
        onChanged();
        return this;
      }
      /**
       * <code>string action = 8;</code>
       */
      public Builder setActionBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        action_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object model_ = "";
      /**
       * <code>string model = 9;</code>
       */
      public java.lang.String getModel() {
        java.lang.Object ref = model_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          model_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string model = 9;</code>
       */
      public com.google.protobuf.ByteString
          getModelBytes() {
        java.lang.Object ref = model_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          model_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string model = 9;</code>
       */
      public Builder setModel(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        model_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string model = 9;</code>
       */
      public Builder clearModel() {
        
        model_ = getDefaultInstance().getModel();
        onChanged();
        return this;
      }
      /**
       * <code>string model = 9;</code>
       */
      public Builder setModelBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        model_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object requestString_ = "";
      /**
       * <code>string requestString = 10;</code>
       */
      public java.lang.String getRequestString() {
        java.lang.Object ref = requestString_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          requestString_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string requestString = 10;</code>
       */
      public com.google.protobuf.ByteString
          getRequestStringBytes() {
        java.lang.Object ref = requestString_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          requestString_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string requestString = 10;</code>
       */
      public Builder setRequestString(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        requestString_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string requestString = 10;</code>
       */
      public Builder clearRequestString() {
        
        requestString_ = getDefaultInstance().getRequestString();
        onChanged();
        return this;
      }
      /**
       * <code>string requestString = 10;</code>
       */
      public Builder setRequestStringBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        requestString_ = value;
        onChanged();
        return this;
      }

      private long userId_ ;
      /**
       * <code>int64 userId = 11;</code>
       */
      public long getUserId() {
        return userId_;
      }
      /**
       * <code>int64 userId = 11;</code>
       */
      public Builder setUserId(long value) {
        
        userId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 userId = 11;</code>
       */
      public Builder clearUserId() {
        
        userId_ = 0L;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:CacheElasticProcessQueue)
    }

    // @@protoc_insertion_point(class_scope:CacheElasticProcessQueue)
    private static final org.grpc.proto.CacheElasticProcessQueueOuterClass.CacheElasticProcessQueue DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.grpc.proto.CacheElasticProcessQueueOuterClass.CacheElasticProcessQueue();
    }

    public static org.grpc.proto.CacheElasticProcessQueueOuterClass.CacheElasticProcessQueue getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<CacheElasticProcessQueue>
        PARSER = new com.google.protobuf.AbstractParser<CacheElasticProcessQueue>() {
      @java.lang.Override
      public CacheElasticProcessQueue parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new CacheElasticProcessQueue(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<CacheElasticProcessQueue> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<CacheElasticProcessQueue> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public org.grpc.proto.CacheElasticProcessQueueOuterClass.CacheElasticProcessQueue getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CacheElasticProcessQueue_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_CacheElasticProcessQueue_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\036CacheElasticProcessQueue.proto\"\346\001\n\030Cac" +
      "heElasticProcessQueue\022\n\n\002id\030\001 \001(\003\022\021\n\tcre" +
      "atedAt\030\002 \001(\t\022\021\n\tupdatedAt\030\003 \001(\t\022\016\n\006statu" +
      "s\030\004 \001(\005\022\025\n\rarchiveStatus\030\005 \001(\005\022\025\n\rproces" +
      "sSource\030\006 \001(\005\022\024\n\014errorMessage\030\007 \001(\t\022\016\n\006a" +
      "ction\030\010 \001(\t\022\r\n\005model\030\t \001(\t\022\025\n\rrequestStr" +
      "ing\030\n \001(\t\022\016\n\006userId\030\013 \001(\003B\020\n\016org.grpc.pr" +
      "otob\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_CacheElasticProcessQueue_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_CacheElasticProcessQueue_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_CacheElasticProcessQueue_descriptor,
        new java.lang.String[] { "Id", "CreatedAt", "UpdatedAt", "Status", "ArchiveStatus", "ProcessSource", "ErrorMessage", "Action", "Model", "RequestString", "UserId", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
